TARGET      := tutorial_11.elf
ENGINEDIR	:= ../../engine

#The Directories, Source, Includes, Objects, Binary and Resources
SRCDIR      := src
INCDIR      := inc
BUILDDIR    := obj
TARGETDIR   := bin
RESDIR      := res
SRCEXT      := cpp
VSMEXT		:= vsm
VCLEXT		:= vcl
VCLPPEXT	:= vclpp
DEPEXT      := d
OBJEXT      := o

#Flags, Libraries and Includes
CFLAGS      := 
LIB         := 
LIBDIRS     := 
INC         := -I$(INCDIR)
INCDEP      := -I$(INCDIR)

include ../Makefile.tutorials-base