LIB         += -ltyra
LIBDIRS     += -L$(ENGINEDIR)/bin
INC         += -I$(ENGINEDIR)/inc/ps2 -I$(ENGINEDIR)/inc/shared
INCDEP		+= -I$(ENGINEDIR)/inc/ps2 -I$(ENGINEDIR)/inc/shared

include ../../Makefile.base

clean-engine:
	cd $(ENGINEDIR) && $(MAKE) cleaner

build-engine:
	cd $(ENGINEDIR) && $(MAKE)

build-release-engine:
	cd $(ENGINEDIR) && $(MAKE) release
